name: task_next_x
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  another_flushbar: ^1.12.30
  logger: ^2.4.0
  lottie: ^3.1.3
  intl: ^0.19.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.2.0

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/animations/lotties/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

